### ISSUE TITLE
Move custom class to tip element (idea)

### ISSUE THREAD

**Issue by LulzAugusto** [720kb/angular-tooltips#121]
Hi!

In the previous versions of angular-tooltips I was able to modify the entire tooltip appearance by setting a custom class. But in this new version, the class is applied to the inner `tip-tip` element, this way I can't - for example - change the tooltip background because I don't have access to the entire container. 

So my suggestion is to change the element that gets the custom class. What do you think about it?

Here's what a did in the previous version:
<img width="302" alt="screen shot 2015-12-01 at 3 38 51 pm" src="https://cloud.githubusercontent.com/assets/254107/11510353/24ffef02-9842-11e5-8b80-df35b1ff45bd.png">

Trying to do to the same thing in the new version:
<img width="176" alt="screen shot 2015-12-01 at 3 39 47 pm" src="https://cloud.githubusercontent.com/assets/254107/11510358/309994a8-9842-11e5-9778-18a6254c1431.png">

**Comment by wouldgo** [comment]
Hi,
I see only now the gitter message, sorry but I was having dinner :smile:.
Anyhow I think you're absolutely right to suggest to move the applied class from the `tip-tip` to the parent element `tip` (I think this is the right choice because it enables all the scenarios you report).

Just for "_another pair of eyes_": @45kb do you see any issues on moving the class to the `tip` element?

**Comment by 45kb** [comment]
Hi, @wouldgo no problems with that.

Thank you @LulzAugusto :+1:

**Comment by wouldgo** [comment]
Could you please give a try to the latest commit?

**Comment by LulzAugusto** [comment]
@wouldgo yes, I'll do it now. 

Have you seen the Gitter messages I left yesterday?

**Comment by LulzAugusto** [comment]
@wouldgo it works! :) 

<img width="294" alt="screen shot 2015-12-02 at 9 14 10 am" src="https://cloud.githubusercontent.com/assets/254107/11530641/19555776-98d5-11e5-8ca7-31a122ce0c19.png">
