### ISSUE TITLE
Gulp Build Issue

### ISSUE THREAD

**Issue by tcrite** [720kb/angular-tooltips#189]
First, thanks for this awesome directive. I'm having an issue with it the gulp build on the server. The angular-tooltips.css file is trying to map to \angular-material\angular-tooltips.css.map.

**Comment by 45kb** [comment]
@tcrite is it possible to reproduce this problem in some way? On a mac perhaprs...?

It seems to work normally here.

**Comment by simonepri** [comment]
@45kb The problem is that the file in
**/dist/angular-tooltips.css** 
at the end presents:
`/*# sourceMappingURL=angular-tooltips.css.map */`

But should not as is not minified.

This generates errors with some gulp plugin
https://github.com/720kb/angular-tooltips/blob/master/dist/angular-tooltips.css#L176

**Comment by simonepri** [comment]
@45kb Could you remove it plase?
Do you want a PR?
Thanks

**Comment by 45kb** [comment]
@45kb hey, yes if you can please PR i'll merge it 👍  thank you
