### ISSUE TITLE
Is it possible to pass data into the template controller?

### ISSUE THREAD

**Issue by DvirH** [720kb/angular-tooltips#201]
I want to load dynamic data according to an element Id. For that I have to pass the element Id to the template controller, but I can't find a way to do so. Any Ideas?

**Comment by steczol** [comment]
Hi! 
Yes, it is possible, since the scope of your controller is a not-isolated child-scope of the linking function`s scope (see ``newScope = scope.$new(false, scope)`` in function ```onTooltipTemplateControllerChange(newValue) ``` . 

Here is what I did:
1. I added new option: ```tooltip-id="myTooltipID"``` to html element I want to know ID of
2. I modified the function ```getAttributesToAdd(element)```  by adding: 
``if (element.attr('tooltip-id') !== undefined){
        attributesToAdd['tooltip-id'] = element.attr('tooltip-id');
        element.removeAttr('tooltip-id');
    }`` now ``myTooltipID`` will be stored in ``$attrs``.
3. Since controller's scope does not inherit `$attrs`, the variable containing myTooltipID has to be exposed to ``$scope``. Therefore I added following line to ```linkingFunction(...)```  : 
`$scope.tooltipID = $attrs.tooltipId; `
4. You should be able now to access the ID in your controller by checking: ``$scope.$parent.tooltipID;``

**Comment by 45kb** [comment]
thanks @steczol for the example.

**Comment by DvirH** [comment]
@steczol  Thanks!
