### ISSUE TITLE
Tooltips appear off page when used in mdSidenav

### ISSUE THREAD

**Issue by BannedForLife** [720kb/angular-tooltips#62]
When using the tooltip on an item in mdSidenav, the tooltip is shown off the page. It seems to be shown at the original position of the mdSidenav (at least I think this is what is happening).

**Comment by 45kb** [comment]
Hi @BannedForLife  try using ```tooltip-try="false"``` and see if it fix

**Comment by BannedForLife** [comment]
Yup tried using that. Same outcome. Tooltip appears off page. I think it could be fixed if I dont initialize the tooltip until the sidenav is open.

**Comment by 45kb** [comment]
Yes, try adding it later :) and let know, better if you post a plunkr or fiddle to show your code :+1:

**Comment by BannedForLife** [comment]
Hey sorry it took so long to reply. Tried using an ng-if to hide it until it was in its correct position but still sis not work. Here is a codepen showing the problem. If you open the right sidenav and hover on the close sidenav button the tooltip will be stick to the right (you need to scroll to the right to see the tooltip).        

http://codepen.io/anon/pen/mJKwXv#0

**Comment by 45kb** [comment]
Hi, i checked the pen thank you for creating it, that's actually a problem when calculating the element position on the screen, since the sidemenu is changing position when toggling.

Need to check deeply to say you something more but the trick should be to use tooltip-lazy="false" so that everytime you mouseover the tooltip is recalculated.

I tried it and looks not working so my guess atm is that something here https://github.com/720kb/angular-tooltips/blob/master/src/js/angular-tooltips.js#L143 is not working

Will tell you more later!

**Comment by 45kb** [comment]
@BannedForLife  maybe there is now a fix for this, please try updating to 0.1.15 and add ```tooltip-scroll="true"```

Should work, otherwise  it's a CSS problem

**Comment by BannedForLife** [comment]
That fix works perfectly, thanks.

**Comment by 45kb** [comment]
@BannedForLife  fantastic, going to close the issue, thank you a lot!
